### ISSUE TITLE
Token Request does not accept URL parameters anymore

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-authorization-server#1549] opened 2024-03-01 12:36 UTC
The token POST request should get the parameters in the POST body. But until version 1.2.0 it was possible to send them in the query-parameter list of the URL. Some of our clients implemented it wrong by using the URLs query-parameters. We didn't notice this until we updated to version 1.2.1 (1.2.2 is also affected).

Was this on purpose? why was this hard-change added into a minor-version-update?

not working:
```http
POST https://test.de/oic/token?code=37k_gt4iP9zoiTGVOkpcKJdLa30GMIeuPpf7_1H4KamlWKpNgm1GYTcUwuku_z3uqcxjsUtc-KPArBB6Be137H9QIwQevWG7BT4Uiw-hCRqVW_XlBrdLn-sSxtL1WKa4&grant_type=authorization_code&redirect_uri=https://test.de/index-vorort-ref.php
Authorization: Basic cGs6MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
```

working
```http
POST https://test.de/oic/token
Authorization: Basic cGs6MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
Content-Type: application/x-www-form-urlencoded

client_id=pk&redirect_uri=https://test.de/index-vorort-ref.php&grant_type=authorization_code&code=37k_gt4iP9zoiTGVOkpcKJdLa30GMIeuPpf7_1H4KamlWKpNgm1GYTcUwuku_z3uqcxjsUtc-KPArBB6Be137H9QIwQevWG7BT4Uiw-hCRqVW_XlBrdLn-sSxtL1WKa4
```

**Comment by jgrandja** [comment] 2024-03-01 15:24
@Captain-P-Goldfish Closing this as a duplicate of gh-1451.

If you need to override this behaviour, you can customize as per [comment](https://github.com/spring-projects/spring-authorization-server/issues/1533#issuecomment-1963874812).

**Closed by jgrandja** 2024-03-01 15:24 UTC
Labels: type: bug
