### ISSUE TITLE
How-to: Test your authorization server

### ISSUE THREAD

**Issue by colin-riddell** [spring-projects/spring-authorization-server#552] opened 2021-12-23 11:54 UTC
What's the best way to test that my implementation of authorization server works for my needs

* Integration testing the authorization server locally using e.g. JUnit. It is possible to write a test with mockMvc calls
* Selenium/Cypress/SoapUI/Postman etc?
* OAuth 2.x conformance suite? Does such a thing exist? Is it proprietary? 

Ref: https://github.com/spring-projects/spring-authorization-server/issues/499

**Comment by sjohnr** [comment] 2021-12-23 19:11
Hi @colin-riddell, thanks for the suggestion! Just for clarity for others, could you update the issue and say just a bit more about your suggestion? For example, you may be suggesting a guide for:

1. Integration testing the authorization server locally using e.g. JUnit
2. Building a test suite for end-to-end OAuth flows using an automated testing tool e.g. Selenium/SoapUI/Postman/etc.
3. Other?

**Comment by jgrandja** [comment] 2022-01-05 15:54
Related gh-258

**Comment by jgrandja** [comment] 2022-12-21 19:36
@colin-riddell 

> Integration testing the authorization server locally using e.g. JUnit. It is possible to write a test with mockMvc calls

Please see the [JUnit integration tests](https://github.com/spring-projects/spring-authorization-server/tree/main/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/config/annotation/web/configurers) that make use of `MockMvc`.

We're also considering adding integration test support via gh-258.

I'm going to close this as a duplicate of gh-258.

**Closed by jgrandja** 2022-12-21 19:36 UTC
Labels: type: enhancement
