### ISSUE TITLE
Add possibility to restrict PKCE to s256 method only

### ISSUE THREAD

**Issue by olr101** [spring-projects/spring-authorization-server#571] opened 2022-01-07 10:22 UTC
**Expected Behavior**
Add the possibility to restrict PKCE method to s256 only (e.g. for authorization code grant for public clients)

**Current Behavior**
Currently both PKCE methods (_s256_ and _plain_) are active by default (which is fine), but they cannot be configured.

**Context**
Sometimes (or often?) it is just not required to support the _plain_ method in production. Therefore disabling _plain_ per configuration could force all clients (that may or may not be under your control) to use the _s256_  method (which is a better protection against eavesdroppers, https://datatracker.ietf.org/doc/html/rfc7636 7.2) and thus decrease the attack surface a little bit.

**Comment by jgrandja** [comment] 2022-01-07 17:52
Thanks for this request @olr101. I agree that `plain` should be disabled by default in order to comply with secure defaults.

We'll look at adding this enhancement.

**Comment by jgrandja** [comment] 2022-02-09 16:03
We should also consider removing support for `plain`.

**Comment by gourav** [comment] 2022-02-22 22:24
Hi @jgrandja 
If it's not assigned to anyone, I would like to work on this one too.

**Comment by jgrandja** [comment] 2022-02-25 19:59
Thanks @gourav. I've scheduled this for `0.3.0`. Let's start work on this after `0.2.3` is out.

**Comment by gourav** [comment] 2022-03-25 06:24
Now that `0.2.3` is released, may I take this up ?

**Comment by jgrandja** [comment] 2022-03-25 13:55
@gourav Just a heads up that our top priority for `0.3.0` is the reference documentation so the team is focusing on that for the next 8 weeks. This means that new features and enhancements will be very light for `0.3.0`.

Having said that, I'm not sure we'll be adding a configuration to disable the `plain` method.

As stated in [7.2 Protection against Eavesdroppers](https://datatracker.ietf.org/doc/html/rfc7636#section-7.2):

> Because of this, "plain" SHOULD NOT be used and exists only for
   compatibility with deployed implementations where the request path is
   already protected.  **The "plain" method SHOULD NOT be used in new
   implementations**, unless they cannot support "S256" for some technical
   reason.

Right now I'm leaning towards removing support for the `plain` method but I'm still thinking it over.

**Comment by gourav** [comment] 2022-03-25 15:26
Hi @jgrandja 

Thank you for letting me know your thoughts on this.

If it's open to contributors, I would like to work on documentation as well.

**Comment by gourav** [comment] 2022-03-29 16:48
Sure. I can work on https://github.com/spring-projects/spring-authorization-server/issues/642

**Comment by jgrandja** [comment] 2022-05-25 00:27
Closing as duplicate of gh-756

**Closed by jgrandja** 2022-05-25 00:27 UTC
Labels: type: enhancement
