### ISSUE TITLE
Token introspection not returning username

### ISSUE THREAD

**Issue by anishcjose** [spring-projects/spring-authorization-server#1787] opened 2024-10-23 21:49 UTC
**Describe the bug**
Token introspection response doesn't have username

**To Reproduce**
configure auth server as opaque token. Configure JDBC token store.  Try to authenticate swager/postman through authorizationCode flow. pass client-id, username and password.  use the token and invoke introspection url.  

**Expected behavior**
as per ietf standard: ( https://datatracker.ietf.org/doc/html/rfc7662#section-2.2) response will be as below.
{
      "active": true,
      "client_id": "l238j323ds-23ij4",
      "username": "jdoe",
      "scope": "read write dolphin",
      "sub": "Z5O3upPC88QrAjx00dis",
      "aud": "https://protected.example.net/resource",
      "iss": "https://server.example.com/",
      "exp": 1419356238,
      "iat": 1419350238,
      "extension_field": "twenty-seven"
     }

//       "username": "jdoe",  is missing in the response. 

https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2TokenIntrospectionAuthenticationProvider.java

After debugging the source code (above class) line number: 143, the username part as TODO and this field is important to know the user who got access to the token.

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment] 2024-10-25 18:30
Closing as duplicate of gh-1713

**Closed by jgrandja** 2024-10-25 18:30 UTC
Labels: type: bug
