### ISSUE TITLE
Make ID Token expiresAt configurable

### ISSUE THREAD

**Issue by git9999999** [spring-projects/spring-authorization-server#1500] opened 2024-01-09 04:02 UTC
**Expected Behavior**
I want to be able to configure the ID Token expiresAt.

**Current Behavior**
The value is a fix value with a todo, see https://github.com/spring-projects/spring-authorization-server/blob/aed93f38acabaeade63b03b8bc5305f9807ef20a/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/token/JwtGenerator.java#L96

**Context**
We use spring authorization server in our test environments. There we have no valuable data. As we use Angular with the Lib https://www.npmjs.com/package/angular-auth-oidc-client we would like to use a refresh token, but this is not supported by spring-authorization-server. This means for us that every user is logged out after 30min as of this fixed value.
The only fix available is to increase this timeout so the testers can test for some hours.

If you agree to this proposal, please let me know. I would try to make a PR.

**Comment by jgrandja** [comment] 2024-01-09 20:13
Closing this as a duplicate of gh-790.

@git9999999 

If an application needs to override the default 30min expiry for an ID Token, you can use an [OAuth2TokenCustomizer](https://docs.spring.io/spring-authorization-server/docs/1.1.4/reference/html/core-model-components.html#oauth2-token-customizer) to override the default.

**Closed by jgrandja** 2024-01-09 20:13 UTC
Labels: type: enhancement

**Comment by git9999999** [comment] 2024-01-10 13:00
Just for documentation, so other peoples have the code ready to fix this problem, here how i fix this issue.

this line did the fix
` context.getClaims().claim("exp", Instant.now().plus(14, HOURS));
`

```      
@Bean
    public OAuth2TokenCustomizer<JwtEncodingContext> tokenCustomizer() {
        return context -> {
            var principal = context.getPrincipal();
            if (Objects.equals(context.getTokenType().getValue(), "access_token") && principal instanceof UsernamePasswordAuthenticationToken) {
                var user = (User) principal.getPrincipal();
                context.getClaims().claim("preferred_username", user.getUsername());
                context.getClaims().claim(USER_ID_CLAIM_KEY.getKey(), user.getUsername());
                context.getClaims().claim("groups", List.of(AZURE_AD_GROUP_AAA_DEV_ADMINPORTAL));
                context.getClaims().claim("correlationId", UUID.randomUUID().toString());
            }
            if (context.getTokenType().getValue().equals(OidcParameterNames.ID_TOKEN)) {
                var user = (User) principal.getPrincipal();
                context.getClaims()
                    .claim("preferred_username", user.getUsername());
                // Overwrite the exp of the ID TOKEN so the tester can longer test
                context.getClaims().claim("exp", Instant.now().plus(5, HOURS));
                context.getClaims().claim("groups", List.of(AZURE_AD_GROUP_AAA_DEV_ADMINPORTAL));
            }
        };
    }
```
