### ISSUE TITLE
Simplify JDBC service customization

### ISSUE THREAD

**Issue by dciarniello** [spring-projects/spring-authorization-server#872] opened 2022-08-24 22:37 UTC
I understand that it is difficult (impossible?) to come provide implementations that work out of the box with all DBs but it would be helpful if the default implementations were simpler to customize.

For example, I'm finding that customizing JdbcOAuth2AuthorizationService to handle mariadb to be somewhat cumbersome.
The mariadb jdbc driver, for some reason that is not entirely clear to me, sets the BLOB column type to LONGVARBINARY which JdbcOAuth2AuthorizationService does not handle.  It seemed that the simplest way to deal with this was to override a method and map LONGVARBINARY to BLOB so that the rest of the code could handle it without further changes.  

That is simple enough with JdbcOAuth2AuthorizationService.OAuth2AuthorizationParametersMapper#apply with something like:

```
@Override
apply(OAuth2Authorization authorization) {
  return super.apply(authorization).stream.map(v -> {
	if(v.getSqlType() == Types.LONGVARBINARY && v.getValue() != null) {
		return new SqlParameterValue(Types.BLOB, ((String)v.getValue()).getBytes(StandardCharsets.UTF_8));
	}
	return v;
}).collect(Collectors.toList());

```

A similar operation would be required for JdbcOAuth2AuthorizationService#findBy but that method is private so it's not possible to override and overriding the findBy methods that call findBy is not feasible because those method rely heavily on private static members.

The only option that I had, short of completely writing my own implementation, was to make a copy JdbcOAuth2AuthorizationService and make one simple change: 

```
private static SqlParameterValue mapToSqlParameter(String columnName, String value) {
	ColumnMetadata columnMetadata = columnMetadataMap.get(columnName);
	return (Types.BLOB == columnMetadata.getDataType() || Types.LONGVARBINARY == columnMetadata.getDataType()) && StringUtils.hasText(value) ?
			new SqlParameterValue(Types.BLOB, value.getBytes(StandardCharsets.UTF_8)) :
			new SqlParameterValue(columnMetadata.getDataType(), value);
}

```

To my mind, a wholesale copy of a class just to make such a simple change is a bit of overkill.

**Comment by jgrandja** [comment] 2022-08-30 20:40
@dciarniello This appears to be a duplicate of gh-774.

Please see this [comment](https://github.com/spring-projects/spring-authorization-server/issues/550#issuecomment-999750559) as it explains how you can completely override the default schema.

**Closed by jgrandja** 2022-08-30 20:40 UTC
Labels: type: enhancement

**Comment by swurzinger** [comment] 2023-03-22 11:38
I don't think this is a duplicate of #550. In that ticket the suggestion is to customize the implementation using a custom `OAuth2AuthorizationParametersMapper` specific to the database in use. That however does not allow to customize all of the database specific code.

The problem is that JdbcOAuth2AuthorizationService uses some database-specific code internally that is not customizable because it's private and/or static.

Ideally the implementation should be as generic as possible and should allow database-specific adaptations to be made without having to duplicate the whole class.
