### ISSUE TITLE
How-to：the same time，use spring authoriztion server with another SSO（example CAS）?

### ISSUE THREAD

**Issue by beijixing1745** [spring-projects/spring-authorization-server#764] opened 2022-06-05 10:42 UTC
hope feature
1.ourself system use spring authorization server for user login and secure api。at the same time，in some case，our system should use another SSO(example CAS) login the system，how？
2.old spring security oauth2 token can store in redis，in spring authorization server，how to do can save token to redis？
3.Authorization Server Support Authorization Code、Client Credentials、Refresh Token，get a new token by user name and code should use form post and second browser url redirect，how to do can get a new token by user name and code on server side？

**Comment by jgrandja** [comment] 2022-06-14 20:02
Closing this as a duplicate of gh-538.

Also, see [federated identity sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#federated-identity-sample).

**Closed by jgrandja** 2022-06-14 20:02 UTC
Labels: type: enhancement
