### ISSUE TITLE
Scope claim should be space-separated in the access token payload

### ISSUE THREAD

**Issue by nverbos-godaddy** [spring-projects/spring-authorization-server#877] opened 2022-08-27 00:17 UTC
**Describe the bug**
[RFC 8693](https://datatracker.ietf.org/doc/html/rfc8693#section-4.2) says that the `scope` claim in the access token should be "a JSON string containing a space-separated list of scopes associated with the token".  However, the scopes claim is a json array of scopes.

**To Reproduce**
Run the authorization server with default configuration. Generated token have the scope claim represented as a json array:
```
{
  "sub": "amit",
  "aud": "control-room",
  "nbf": 1637159481,
  "scope": [
    "openid",
    "profile"
  ],
  "iss": "http://localhost:9000",
  "exp": 1637159781,
  "iat": 1637159481
}
```

**Expected behavior**
Generated tokens should have the scope claim represented as a JSON string containing a space-separated list of scopes.  The payload for the token should look like the following example:

```
{
  "sub": "amit",
  "aud": "control-room",
  "nbf": 1637159481,
  "scope": "openid profile",
  "iss": "http://localhost:9000",
  "exp": 1637159781,
  "iat": 1637159481
}
```

**Comment by jgrandja** [comment] 2022-08-31 10:46
@nverbos-godaddy The spec you referenced is OAuth 2.0 Token Exchange, which has not been implemented yet (see gh-60).

Furthermore, [RFC 8693](https://datatracker.ietf.org/doc/html/rfc8693#section-4.2) Section 4.2 states:

> OAuth 2.0 Token Introspection [[RFC7662](https://datatracker.ietf.org/doc/html/rfc7662)] already defines the "scope"
   parameter to convey the scopes associated with the token.

The OAuth 2.0 Token Introspection endpoint does return a space-separated list of scopes so this has been implemented to spec.

Since the OAuth 2.0 Token Exchange grant has not been implemented, I'll close this as a duplicate of gh-60.

**Closed by jgrandja** 2022-08-31 10:46 UTC
Labels: type: bug

**Comment by banterCZ** [comment] 2025-02-17 11:54
From my understanding, there is a simple workaround to register a custom `OAuth2TokenCustomizer`.

```java
@Bean
public OAuth2TokenCustomizer<JwtEncodingContext> oAuth2TokenScopeCustomizer() {
    return context -> {
        final String scopeString = String.join(" ", context.getAuthorizedScopes());
        context.getClaims().claim("scope", scopeString);
    };
}
```
