### ISSUE TITLE
Add code samples how to setup authorization server to support PRIVATE_KEY_JWT authentication method.

### ISSUE THREAD

**Issue by marwoj** [spring-projects/spring-authorization-server#747] opened 2022-05-20 14:11 UTC
**Expected Behavior**
Add example to official samples how to setup authorization server to support PRIVATE_KEY_JWT

**Current Behavior**
Currently there is no such example. I've tried to implement it on my own, but it doesn't work. 

**Context**
I've generated private key using command: `openssl genrsa -out private.key 2048`
Then I've created a project - you can find source code here: [https://github.com/marwoj/spring-security-oauth2-private-key_jwt](https://github.com/marwoj/spring-security-oauth2-private-key_jwt)

Steps to reproduce:

1. Run project  `./gradlew bootRun` 
1. Try to get get access token using python script located in resources `python3 ./get-access-token.py`,
1. 401 when accessing `/oauth2/token` endpoin is returned

Despite the fact, that I've configured:
```
   .clientAuthenticationMethod(ClientAuthenticationMethod.PRIVATE_KEY_JWT)
   .authorizationGrantType(AuthorizationGrantType.JWT_BEARER)
```
When accessing: `http://localhost:8080/.well-known/openid-configuration`,  there is no `urn:ietf:params:oauth:grant-type:jwt-bearer` on `grant_types_supported` list

Side note:
Python script creates JWT signed with the same private key.  JWT payload is:
```
{
  "iss": "client1",
  "exp": 1653056943,
  "aud": "http://localhost:8080/oauth2"
}
```

Also related to: https://github.com/spring-projects/spring-authorization-server/issues/746

**Comment by NotFound403** [comment] 2022-05-24 02:41
Yeah! this sample is necessary，I dont think its a good idea to generate keypair with python script. You can see the test class [TestKeys](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/jose/TestKeys.java).

**Comment by NotFound403** [comment] 2022-05-25 02:00
**PRIVATE_KEY_JWT** is one of `ClientAuthenticationMethod`, its used to authenticate the oauth2 client  independent with `grant_type`.   here is my sample:

```java
 
RegisteredClient.withId("yourregisteredclientid")
                .clientId("yourclientid")
                .clientName("yourapp")
                //  use  private key jwt
                .clientAuthenticationMethod(ClientAuthenticationMethod.PRIVATE_KEY_JWT)
                // grant types 
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
                .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
                //    your client callback
                .redirectUri("http://127.0.0.1:8082/foo/bar")
                .scope("message.read")
                .scope("message.write")
                .clientSettings(ClientSettings.builder()     
                // here is the jwkset alg
                   .tokenEndpointAuthenticationSigningAlgorithm(SignatureAlgorithm.RS256)
                        // public key  jwtseturi  providered by  your oauth2 client   
                        .jwkSetUrl("http://localhost:8082/oauth2/jwks")
                        .build())
                .build();
```
you can generate rsa keypair formatted **PKCS12** via **keytool** , like that:
```java
public class JwkResolver  {


    @SneakyThrows
    public JWK apply() {
         
        String path = "client.jks";
        String alias = "jose";
        String pass = "yourpass";
        ClassPathResource resource = new ClassPathResource(path);
        KeyStore jks = KeyStore.getInstance("jks");
        char[] pin = pass.toCharArray();
        jks.load(resource.getInputStream(), pin);
        return RSAKey.load(jks, alias, pin);
    }
}
```

and then offer a client jwtseturi with anonymous access:
```java
@RestController
public class JwkController {
    private final JwkResolver resolver = new JwkResolver();

    /**
     * jwkSetUri endpoint
     *
     * @return pub jwk
     */
    @SneakyThrows
    @GetMapping(value = "/oauth2/jwks")
    public Map<String, Object> jwks() {
 
        JWK jwk = resolver.apply();
        JWKSet jwkSet = new JWKSet(jwk);
 
        return JSONObjectUtils.parse(jwkSet.toString());
    }
}
```

**Comment by marwoj** [comment] 2022-06-01 12:15
Hi @ISpectruM this is not the case, it was a typo when converting from postman to curl. After update still it does not work.

What I've tried to provide bean jwkSource and jwtDecoder, still it does not work

```kotlin
    @Bean
    fun jwtDecoder(jwkSource: JWKSource<SecurityContext>): JwtDecoder? {
        return OAuth2AuthorizationServerConfiguration.jwtDecoder(jwkSource)
    }

    @Bean
    fun jwkSource(): JWKSource<SecurityContext> {
        val rsaKey: RSAKey = getRsa()
        val jwkSet = JWKSet(rsaKey)
        return JWKSource<SecurityContext> { jwkSelector, _ -> jwkSelector.select(jwkSet) }
    }

    private fun getRsa(): RSAKey {
        val keystore = KeyStore.getInstance("PKCS12");
        keystore.load(this::class.java.classLoader.getResourceAsStream("pkcs12keystore.p12"), "password".toCharArray())
           
        val privateKey: RSAPrivateKey = keystore.getKey("alias", "password".toCharArray()) as RSAPrivateKey

        val cert: Certificate = keystore.getCertificate("alias")!!
        val publicKey: RSAPublicKey = cert.publicKey as RSAPublicKey

        return RSAKey.Builder(publicKey)
            .privateKey(privateKey)
            .keyID(UUID.randomUUID().toString())
            .build()
    }
```

**Comment by Shryne** [comment] 2022-06-02 10:15
I can confirm that `authorizationGrantType(AuthorizationGrantType.JWT_BEARER)` doesn't change anything on `.well-known`. I also tried other settings, and I didn't manage to change the shown `grant_types_supported `. The default is:
```json
 "grant_types_supported": [
    "authorization_code",
    "client_credentials",
    "refresh_token"
  ],
```
And it stays like this no matter the settings. The same goes for this:
```json
"token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt"
  ],
```

Additionally, I also tried a request on `/oauth2/token` (by bypassing the JWT validator stuff) with a `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer` query and it fails with "unsupported_grant_type". This error is created by `OAuth2TokenEndpointFilter`. This class compares the given grant type with the ones supported. Unfortunately, the supported grant types are hardcoded in the constructor:
```java
public OAuth2TokenEndpointFilter(AuthenticationManager authenticationManager, String tokenEndpointUri) {
    Assert.notNull(authenticationManager, "authenticationManager cannot be null");
    Assert.hasText(tokenEndpointUri, "tokenEndpointUri cannot be empty");
    this.authenticationManager = authenticationManager;
    this.tokenEndpointMatcher = new AntPathRequestMatcher(tokenEndpointUri, HttpMethod.POST.name());
    this.authenticationConverter = new DelegatingAuthenticationConverter(
    Arrays.asList(
        new OAuth2AuthorizationCodeAuthenticationConverter(),
	new OAuth2RefreshTokenAuthenticationConverter(),
	new OAuth2ClientCredentialsAuthenticationConverter())
    );
}
```
Since none of these converters are able to convert for jwt-bearer, it fails:
```java
	Authentication authorizationGrantAuthentication = this.authenticationConverter.convert(request);
	if (authorizationGrantAuthentication == null) {
		throwError(OAuth2ErrorCodes.UNSUPPORTED_GRANT_TYPE, OAuth2ParameterNames.GRANT_TYPE);
	}
```

It really looks like using a jwt is only possible as long as a regular login is performed. This way you get the authorization code and can perform a `/oauth2/token` call with it and add the jwt. I have no idea if that's intended because I thought when it was implemented that you can use it as a grant type as well. 
At least I would expect an error for calling `authorizationGrantType(AuthorizationGrantType.JWT_BEARER)`...

**Comment by marwoj** [comment] 2022-06-02 20:08
@sjohnr It explains a lot :)

**Comment by jgrandja** [comment] 2022-06-13 20:05
@marwoj As mentioned by @sjohnr in previous comment, gh-546 will address JWT authorization grant support.

I logged gh-781 to address a `private_key_jwt` client authentication sample. Closing this as a duplicate.

**Closed by jgrandja** 2022-06-13 20:05 UTC
Labels: type: enhancement
