### ISSUE TITLE
The postgresql database is not supported, please help

### ISSUE THREAD

**Issue by yjySun** [spring-projects/spring-authorization-server#1496] opened 2024-01-05 10:58 UTC
I used the postgresql database and got an error when trying to access it.
![企业微信截图_17044518511129](https://github.com/spring-projects/spring-authorization-server/assets/54382029/3f083ffe-6b68-447f-ae99-5e3a113838ab)
![企业微信截图_17044520377432](https://github.com/spring-projects/spring-authorization-server/assets/54382029/ca066bca-7727-40d9-80dc-300d6bb4f7e6)
![企业微信截图_17044523081258](https://github.com/spring-projects/spring-authorization-server/assets/54382029/8c5a19bb-2cd2-40b0-9b7a-28a28c31f232)

**Comment by jgrandja** [comment] 2024-01-08 18:34
Closing as duplicate of gh-560

**Closed by jgrandja** 2024-01-08 18:34 UTC
Labels: type: bug
