### ISSUE TITLE
Allow configuration for authorization code time-to-live

### ISSUE THREAD

**Issue by guo-jun-airwallex** [spring-projects/spring-authorization-server#642] opened 2022-03-04 10:21 UTC
**Expected Behavior**
Should allow different clients to customize different authorization code time-to-live

**Current Behavior**
The authorization code time-to-live is always 5 minutes.

**Context**
```
private OAuth2AuthorizationCode generateAuthorizationCode() {
		Instant issuedAt = Instant.now();
		Instant expiresAt = issuedAt.plus(5, ChronoUnit.MINUTES);		// TODO Allow configuration for authorization code time-to-live
		return new OAuth2AuthorizationCode(this.authorizationCodeGenerator.get(), issuedAt, expiresAt);
	}
```
The TODO in `generateAuthorizationCode` is already existed in two minor version.
Can I know the ETA of this feature.
I hope there is a `getAuthorizationCodeTimeToLive` method in `TokenSettings` class to customize authorization code time-to-live.

**Comment by arunsah** [comment] 2022-03-07 04:21
Hi Guo,
Not sure, but seem like you might be looking for this:

```java
// client is simple DTO fetched from DB

RegisteredClient.Builder registeredClientBuilder = RegisteredClient.withId(client.getId())
        .clientId(client.getClientName()).clientName(client.getClientName()).clientSecret(client.getClientSecret());
// some other settings

var tokenSettingsBuilder = TokenSettings.builder();

// access token time to live settings
tokenSettingsBuilder.accessTokenTimeToLive(Duration.ofSeconds(client.getAccessTokenTimeToLiveInSeconds()));
tokenSettingsBuilder.refreshTokenTimeToLive(Duration.ofSeconds(client.getRefreshTokenTimeToLiveInSeconds()));
tokenSettingsBuilder.reuseRefreshTokens(client.isReuseRefreshTokens());

registeredClientBuilder.tokenSettings(tokenSettingsBuilder.build());

RegisteredClient registeredClient =  registeredClientBuilder.build();

```

Thanks,
Arun.

**Comment by jgrandja** [comment] 2022-03-11 20:32
Thanks @guo-jun-airwallex. We'll look at adding this soon.

**Comment by jgrandja** [comment] 2022-03-30 10:33
The issue is yours @gourav. Please review the [Getting Started](https://github.com/spring-projects/spring-authorization-server#getting-started) in case you haven't already. Thanks.

**Comment by gourav** [comment] 2022-05-31 14:27
Hi @jgrandja 
Unfortunately, I am not able to contribute due to health issues I am facing currently. 

I apologise for the delay and inconvenience. 

Please feel free to assign this issue to another contributor. 

I hope to be back to contribution post recovery. 

Thank you.

**Comment by jgrandja** [comment] 2022-05-31 16:01
@gourav Take care of your health. There is nothing more important.

We have endless work over here so whenever you have your health back in order and ready to contribute please reach out.

Wish you the best.

**Comment by appchemist** [comment] 2022-06-13 15:25
Hi @jgrandja.

**Comment by jgrandja** [comment] 2022-06-15 09:04
Thanks for the offer @appchemist. The issue is yours.

**Comment by appchemist** [comment] 2022-06-19 12:50
Hi, @jgrandja 

I think ID Token also requires time-to-live configuration.
```
Instant issuedAt = Instant.now();
Instant expiresAt;
if (OidcParameterNames.ID_TOKEN.equals(context.getTokenType().getValue())) {
	// TODO Allow configuration for ID Token time-to-live
	expiresAt = issuedAt.plus(30, ChronoUnit.MINUTES);
} else {
	expiresAt = issuedAt.plus(registeredClient.getTokenSettings().getAccessTokenTimeToLive());
}
```

**Comment by jgrandja** [comment] 2022-06-21 17:34
@appchemist We're holding off on the ID token TTL setting as the required changes are more involved than authorization code TTL.

FYI, I'm off on PTO for a couple of weeks so I'll review your PR when I return.

**Closed** 2022-07-19 18:24 UTC
Labels: type: enhancement
