### ISSUE TITLE
`Implement the core services with JPA` guide cant  complete authorization

### ISSUE THREAD

**Issue by hezhongfeng** [spring-projects/spring-authorization-server#893] opened 2022-09-16 02:51 UTC
**Describe the bug**

when I `Implement the core services with JPA` ，will catch a error circle

<img width="1200" alt="176DFECC-B109-47AB-8227-89E87D401B05" src="https://user-images.githubusercontent.com/12163050/190546002-5d6f5714-0b33-4c41-ab85-bc64ec134562.png">
<img width="1201" alt="9626E138-126C-48D7-8C2C-1A4EC6E12C53" src="https://user-images.githubusercontent.com/12163050/190546006-a5fabcd8-b3bc-43a4-99af-ce71999ea7a7.png">

**To Reproduce**

1. Run My Sample(use local mysql) as server
2. Run the Resource Server sample in `spring-authorization-server`
3. run the messages-client sample in `spring-authorization-server`

**Expected behavior**

could get accesstoken and get message

**Sample**

[My demo](https://github.com/hezhongfeng/authorization-server-demo).

**Comment by sjohnr** [comment] 2022-09-27 16:04
@hezhongfeng thanks for reaching out!

We have integration tests for our guides that ensure that the code works as expected. The tests use the h2 database. I have also just confirmed that adding these services/entities/repositories into a Spring Boot application with the h2 database and the configuration from the [Getting Started](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html#developing-your-first-application) page works out of the box with the default samples of client and resource server.

The only difference I can spot in your sample is the use of MySQL and a custom data initialization script. There may be issues with MySQL that the guide does not account for, and you will need to make some adjustments based on your chosen database.

I'm going to close this for now as the code for the JPA guide works as intended with a sample database (h2). If you find any specific issues with MySQL, please share here and we can open specific enhancements for the guide if it makes sense to do so!

**Closed by sjohnr** 2022-09-27 16:04 UTC
Labels: type: bug

**Comment by hezhongfeng** [comment] 2022-09-28 00:43
ok, I will change mysql to h2.

**Comment by hezhongfeng** [comment] 2022-09-28 06:22
I have known how to add client，need to add accessTokenFormat attribute.

```
String tokenSettingString =
		"{\"@class\":\"java.util.Collections$UnmodifiableMap\",\"settings.token.reuse-refresh-tokens\":true,\"settings.token.id-token-signature-algorithm\":[\"org.springframework.security.oauth2.jose.jws.SignatureAlgorithm\",\"RS256\"],\"settings.token.access-token-time-to-live\":[\"java.time.Duration\",300.000000000],\"settings.token.access-token-format\":{\"@class\":\"org.springframework.security.oauth2.core.OAuth2TokenFormat\",\"value\":\"self-contained\"},\"settings.token.refresh-token-time-to-live\":[\"java.time.Duration\",3600.000000000]}";

client.setTokenSettings(tokenSettingString);
```

**Comment by hezhongfeng** [comment] 2022-09-28 06:23
H2 or mysql is ok
