### ISSUE TITLE
when I use this library with the newest spring-boot,I got an error

### ISSUE THREAD

**Issue by zwjsexcalibur** [spring-projects/spring-authorization-server#613] opened 2022-01-31 08:20 UTC
when i user this libary with spring-boot-starter-parent(2.6.3),I got error like this :
java.lang.IllegalAccessError: tried to access class org.springframework.security.oauth2.jwt.JoseHeader from class org.springframework.security.oauth2.server.authorization.authentication.JwtUtils
	at org.springframework.security.oauth2.server.authorization.authentication.JwtUtils.headers(JwtUtils.java:46) ~[spring-security-oauth2-authorization-server-0.2.2.jar:0.2.2]
	at org.springframework.security.oauth2.server.authorization.authentication.OAuth2AuthorizationCodeAuthenticationProvider.authenticate(OAuth2AuthorizationCodeAuthenticationProvider.java:172) ~[spring-security-oauth2-authorization-server-0.2.2.jar:0.2.2]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-5.6.1.jar:5.6.1]
	at org.springframework.security.oauth2.server.authorization.web.OAuth2TokenEndpointFilter.doFilterInternal(OAuth2TokenEndpointFilter.java:165) ~[spring-security-oauth2-authorization-server-0.2.2.jar:0.2.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.1.jar:5.6.1]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.6.1.jar:5.6.1]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.6.1.jar:5.6.1]

this error occured by using authorization_code.

but the error will not occur  if I use spring-boot-starter-parent(2.3.4).

i use the this project(https://github.com/xpp1109/spring-security-lt5-oauth2.git) as example.And change the spring-boot-starter-parent version the error while occur.

**Comment by zwjsexcalibur** [comment] 2022-01-31 08:21
the spring-authorization-server also use 0.2.2

**Comment by sjohnr** [comment] 2022-01-31 18:16
Thanks for the report, @zwjsexcalibur and welcome to the project!

I believe this is a duplicate of gh-518 which will be resolved with gh-594. See [this comment](https://github.com/spring-projects/spring-authorization-server/issues/518#issuecomment-1017302836) and the next one to see if that helps resolve your issue.

I'm going to close this as a duplicate, but if your error is somehow different and requires a different workaround we can discuss it, or even re-open the issue if needed. Please do let me know if it works or you get stuck!

**Closed by sjohnr** 2022-01-31 18:16 UTC
Labels: type: bug
