### ISSUE TITLE
MessagesClientApplication not listening on the defined port

### ISSUE THREAD

**Issue by zubair-farooqui** [spring-projects/spring-authorization-server#853] opened 2022-08-14 22:39 UTC
**Describe the bug**
When running MessagesClientApplication, it sayings that the application started but is not listening on the port (8080). When I opened http://127.0.0.1:8080/, the browser is responding ERR_EMPTY_RESPONSE

**To Reproduce**
Just run MessagesClientApplication

**Expected behavior**
MessagesClientApplication should listen on the configured port (8080).

**Sample**
<img width="1393" alt="Screenshot 2022-08-15 at 2 35 29 AM" src="https://user-images.githubusercontent.com/12321796/184557330-fc5fa989-25c0-403b-8877-fd355778c717.png">

<img width="1757" alt="image" src="https://user-images.githubusercontent.com/12321796/184557394-2651e5c8-1e5b-4dd3-b933-0faa84c84e20.png">

**Comment by jgrandja** [comment] 2022-08-17 18:44
@zubair-farooqui The [messages-sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#messages-sample) has been working for a while now without any issues reported. Can you try rebooting your machine and start over again. If the issue is still happening, can you try on another machine? I suspect it's environment related.

**Comment by spring-projects-issues** [comment] 2022-08-24 18:46
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-08-31 18:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-08-31 18:46 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
