### ISSUE TITLE
Can this use in a webflux project?

### ISSUE THREAD

**Issue by 1760793695** [spring-projects/spring-authorization-server#1114] opened 2023-03-07 14:08 UTC
Can this use in a webflux project?

**Comment by jgrandja** [comment] 2023-03-07 15:07
Closing as duplicate of gh-152. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644).

**Closed by jgrandja** 2023-03-07 15:07 UTC
Labels: type: enhancement

**Comment by 1760793695** [comment] 2023-03-07 18:05
> Closing as duplicate of gh-152. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644).

thanks,i got know
