### ISSUE TITLE
Support Webflux

### ISSUE THREAD

**Issue by ithander** [spring-projects/spring-authorization-server#1669] opened 2024-07-12 02:42 UTC
**Expected Behavior**

We strongly request the addition of webflux support, as we are an authentication center that interfaces with many clients and each client has many users. And OAuth2 Server doesn't have many endpoints either
**Current Behavior**

**Context**

**Comment by jgrandja** [comment] 2024-07-16 09:26
Closing as duplicate of gh-418.

**Closed by jgrandja** 2024-07-16 09:26 UTC
Labels: type: enhancement
