### ISSUE TITLE
Cleanup of expired oauth2_authorization codes

### ISSUE THREAD

**Issue by aka-unk** [spring-projects/spring-authorization-server#1534] opened 2024-02-08 16:42 UTC
**Expected Behavior**
The expired authorization code records, should be cleaned from the oauth2_authorization table.
**Current Behavior**
The generated record stays there permanently and the table just keep growing.
**Context**
I hope the above lines already define the full context. 
Perhaps, a scheduler can check is there any expired record in the table and cleanup.

**Comment by jgrandja** [comment] 2024-02-26 11:25
Closing as duplicate of gh-556 and gh-1266

**Closed by jgrandja** 2024-02-26 11:25 UTC
Labels: type: enhancement
