### ISSUE TITLE
Endless generation of pair authorization code/token after successfull login

### ISSUE THREAD

**Issue by carloterzo** [spring-projects/spring-authorization-server#888] opened 2022-09-12 07:32 UTC
Hi guys,
during a development of a SPA with an authorization code flow as login, I've experienced a strange behaviour of authorization server. 
With a simple bug in frontend side it is possibile, after a successful login, make a loop of code and token request that generate endless writing of rows in database inside oauth2_authorization table.

Watching the code inside JdbcOAuth2AuthorizationService we can see that it's used a random generated id to fetch existing code/token and it changes on every request: 

```
	@Override
	public void save(OAuth2Authorization authorization) {
		Assert.notNull(authorization, "authorization cannot be null");
		OAuth2Authorization existingAuthorization = findById(authorization.getId());
		if (existingAuthorization == null) {
			insertAuthorization(authorization);
		} else {
			updateAuthorization(authorization);
		}
	}
```

My questions are:
 Why the find method doesn't use for example registered_client_id and principal_name to identify the same request from the same client to avoid endless rows writing?
 How I can avoid (server side) that a simple bug can flood silently the backend database?
 There are some best practices in writing or deploying the authorization server? 

Thanks in advance,

**Comment by jgrandja** [comment] 2022-09-13 11:36
Closing as duplicate of gh-873

**Closed by jgrandja** 2022-09-13 11:36 UTC
Labels: type: bug
