### ISSUE TITLE
OAuth2AuthorizationCodeRequestAuthenticationConverter saves PKCE parameters as additional parameters 

### ISSUE THREAD

**Issue by martin-lindstrom** [spring-projects/spring-authorization-server#1251] opened 2023-05-31 18:07 UTC
When fixing the bug reported in issue #1250 I noticed that the `convert` method in `OAuth2AuthorizationCodeRequestAuthenticationConverter` saves the PKCE parameters (code_challenge and code_challenge_method) not only in the resulting Authentication object, but also as additionalParameters. Clearly, this can't be what is wanted?

**Comment by sjohnr** [comment] 2023-06-01 20:59
Thanks for reaching out @martin-lindstrom, and thanks for working on that PR.

This is currently where the `code_challenge` and `code_challenge_method` are sourced from:

https://github.com/spring-projects/spring-authorization-server/blob/9c1ec348afcaa5c68d058d0b9b38fda405393edc/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/CodeVerifierAuthenticator.java#L95-L96

https://github.com/spring-projects/spring-authorization-server/blob/9c1ec348afcaa5c68d058d0b9b38fda405393edc/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/CodeVerifierAuthenticator.java#L112-L113

 Since the authorization request and the token request are made by two different authenticated principals (user vs client), the entirety of the original request is carried through so additional parameters can be easily used for additional validation. I believe there are many such scenarios in the various specs that would require this support. Not all parameters would be preserved in the user's principal (`Authentication`) object.

Since I believe this is working as designed, I'm going to close this as answered. Let me know if you see something I don't. If you do believe this is a bug, please provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by sjohnr** 2023-06-01 20:59 UTC
Labels: type: bug
