### ISSUE TITLE
Support of WebFlux

### ISSUE THREAD

**Issue by 403Unauthorized** [spring-projects/spring-authorization-server#418] opened 2021-08-24 06:59 UTC
** Purpose**
Are you planning to add support for WebFlux?

I'm currently using Spring WebFlux in my application, so I really need that support.

**Expected**
If you've already had support for it, can you please refer me a doc to it?

If not, I want to be a part of contributor for this enhancement if you are planning to do it.

**Comment by jgrandja** [comment] 2021-08-24 12:48
@403Unauthorized Closing as duplicate of gh-152. See [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644)

**Closed by jgrandja** 2021-08-24 12:48 UTC
Labels: status: waiting-for-triage
