### ISSUE TITLE
Error configuring for database mariadb 

### ISSUE THREAD

**Issue by publicocean0** [spring-projects/spring-authorization-server#993] opened 2022-11-29 15:45 UTC
**Describe the bug**
I tryed to configure with mariadb . I created the 3 tables as defined in the folder resources in the project. The fields with datatype timestamp dont accept default null. In addition when i try to login in the app client appears the error below.

**To Reproduce**
try to login 

**Expected behavior**
error during login

**Sample**

Caused by: java.sql.SQLSyntaxErrorException: (conn=34) Could not convert [{"@class":"java.util.Collections$UnmodifiableMap","java.security.Principal":{"@class":"org.springframework.security.authentication.UsernamePasswordAuthenticationToken","authorities":["java.util.Collections$UnmodifiableRandomAccessList",[{"@class":"org.springframework.security.core.authority.SimpleGrantedAuthority","authority":"ROLE_USER"}]],"details":{"@class":"org.springframework.security.web.authentication.WebAuthenticationDetails","remoteAddress":"0:0:0:0:0:0:0:1","sessionId":"8DFC9AB94CC27404DACA40DE225C3C6F"},"authenticated":true,"principal":{"@class":"org.springframework.security.core.userdetails.User","password":null,"username":"user1","authorities":["java.util.Collections$UnmodifiableSet",[{"@class":"org.springframework.security.core.authority.SimpleGrantedAuthority","authority":"ROLE_USER"}]],"accountNonExpired":true,"accountNonLocked":true,"credentialsNonExpired":true,"enabled":true},"credentials":null},"org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest":{"@class":"org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest","authorizationUri":"http://localhost:9000/oauth2/authorize","authorizationGrantType":{"value":"authorization_code"},"responseType":{"value":"code"},"clientId":"messaging-client","redirectUri":"http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc","scopes":["java.util.Collections$UnmodifiableSet",["openid","profile"]],"state":"YjEMJ2JDHIBp3fXgI_0ONWGj-C4rXkp1Nhxv76lBk5k=","additionalParameters":{"@class":"java.util.Collections$UnmodifiableMap","nonce":"FRpIQzY0EJkXkQ-52ZsSZR9SkSUACAMpbQG-A3pg-DQ"},"authorizationRequestUri":"http://localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=openid%20profile&state=YjEMJ2JDHIBp3fXgI_0ONWGj-C4rXkp1Nhxv76lBk5k%3D&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc&nonce=FRpIQzY0EJkXkQ-52ZsSZR9SkSUACAMpbQG-A3pg-DQ","attributes":{"@class":"java.util.Collections$UnmodifiableMap"}},"state":"cfUaG3bvcm-F3DCJHTv2jpI50ZLGJuaVFFP0ZLpxlgE="}] to -4

**Comment by jgrandja** [comment] 2022-12-09 22:45
@publicocean0 Closing this as a duplicate of gh-774.

For additional details, please see this [comment](https://github.com/spring-projects/spring-authorization-server/issues/550#issuecomment-999750559).

**Closed by jgrandja** 2022-12-09 22:45 UTC
Labels: type: bug
