### ISSUE TITLE
OAuth2AuthenticationProviderUtils is package private and should be public

### ISSUE THREAD

**Issue by quanticworld** [spring-projects/spring-authorization-server#1304] opened 2023-07-17 14:27 UTC
**Describe the bug**
class `OAuth2AuthenticationProviderUtils` is package private (on purpose or public keyword missing?). Thus it cannot be used outside the library.
Is it possible to have it public, so that `OAuth2AuthenticationProviderUtils.getAuthenticatedClientElseThrowInvalidClient()` can be used outside the library ?

**To Reproduce**
Try to `import org.springframework.security.oauth2.server.authorization.authentication.OAuth2AuthenticationProviderUtils`.

**Expected behavior**
Should be accessible

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment] 2023-07-17 14:58
Closing as duplicate of gh-1290. See [comment](https://github.com/spring-projects/spring-authorization-server/issues/1290#issuecomment-1634297392).

**Closed by jgrandja** 2023-07-17 14:58 UTC
Labels: type: bug

**Comment by OrangeDog** [comment] 2025-05-08 16:12
Anyone writing a custom provider will want both these methods, and they're already forced into unreasonable amounts of copy-pasting the library code.
