### ISSUE TITLE
Using client_secret with + sign fail.

### ISSUE THREAD

**Issue by Martin-Office** [spring-projects/spring-authorization-server#1410] opened 2023-10-17 18:33 UTC
**Describe the bug**
Using a client_secret with this value a+b always fail with:
OAuth2AuthenticationException: Client authentication failed: client_secret

Issue cause by class ClientSecretBasicAuthenticationConverter method convert:
	clientSecret = URLDecoder.decode(credentials[1], StandardCharsets.UTF_8.name());

**To Reproduce**
Create a client with a client_secret value of "{noop}a+b"

**Expected behavior**
I expecting the password use in the request to match the password set for the clientId.
Or define character set possible for password. 

**Sample**
System.out.println("Expected value is a+b but got: " + URLDecoder.decode("a+b", StandardCharsets.UTF_8));

**Comment by jgrandja** [comment] 2023-10-20 10:34
@Martin-Office I could not reproduce the issue.

I changed this line:

https://github.com/spring-projects/spring-authorization-server/blob/8f2ea490adbfa00486524b443d8d7e6289224d98/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/config/annotation/web/configurers/OAuth2ClientCredentialsGrantTests.java#L205

to:

`RegisteredClient registeredClient = TestRegisteredClients.registeredClient2().clientSecret("a+b").build();`

and the client authenticated successfully.

Please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue so I can look at it further.

**Comment by Martin-Office** [comment] 2023-10-20 14:47
Ok, Maybe I forgot to say the client secret was set in the application.yaml in this format: 
client-secret: "{noop}secret+2"
Maybe the fact that I used noop encoding is the issue.

**Comment by Martin-Office** [comment] 2023-10-20 19:21
I was able to reproduce with a simple example on Github. 
https://github.com/Martin-Office/SpringBootOAuth2-ClientSecret/tree/showcase_client_secret_bug/SpringBootOauth2AuthorizationServer

**Comment by jgrandja** [comment] 2023-10-26 10:53
@Martin-Office The reproducer is incorrect.

> Run curl with proper values from previous steps. Decoded value of Authorization: Basic Y2xpZW50OnNlY3JldCsy is client:secret+2

`secret+2` should be `secret%2B2`

Please review the spec, in [2.4.1. ](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#section-2.4.1)[Client Secret](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#name-client-secret):

> The client identifier is encoded using the application/x-www-form-urlencoded encoding algorithm per Appendix B, and the encoded value is used as the username; the client secret is encoded using the same algorithm and used as the password.

The current behaviour is implemented to spec. Closing this as invalid.

**Closed by jgrandja** 2023-10-26 10:53 UTC
Labels: status: feedback-provided
