### ISSUE TITLE
Support password grant type

### ISSUE THREAD

**Issue by Cesco94** [spring-projects/spring-authorization-server#505] opened 2021-11-19 16:05 UTC
Hello,
I tried to add `AuthorizationGrantType.PASSWORD` while building the `RegisteredClient` object, like this:

```
RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
				...
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
				.authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
				.authorizationGrantType(AuthorizationGrantType.PASSWORD)
				...
				.build();
```
				
Using Postman, the error I get is: 
```
{
    "error_description": "OAuth 2.0 Parameter: grant_type",
    "error": "unsupported_grant_type",
    "error_uri": "https://datatracker.ietf.org/doc/html/rfc6749#section-5.2"
}
```

Any plans for future baselines to support this grant type?
Thank you!

**Comment by dattebayorob** [comment] 2021-11-20 01:47
See #466

**Comment by Cesco94** [comment] 2021-11-22 09:08
I see, thank you. So it would be nice to remove the constant `AuthorizationGrantType.PASSWORD` to avoid misunderstanding. Thanks!

**Comment by jgrandja** [comment] 2021-11-25 20:05
Closing as duplicate of gh-343

**Closed by jgrandja** 2021-11-25 20:05 UTC
Labels: status: waiting-for-triage
