### ISSUE TITLE
In Dynamic Client Registration, there's no handling for ClientAuthenticationMethod.NONE

### ISSUE THREAD

**Issue by emyasa** [spring-projects/spring-authorization-server#625] opened 2022-02-12 19:38 UTC
**Describe the bug**
In Dynamic Client Registration, considering that it uses PKCE, it isn't possible to set the clientAuthenticationMethod to none. (It always defaults to CLIENT_BASIC_SECRET)
![image](https://user-images.githubusercontent.com/70507913/153725395-e3422bca-6d11-4c37-a891-52f83d187f8c.png)

**To Reproduce**
 1. Configure the authorization server to include OidcClientRegistrationEndpointFilter:
 `        Customizer<OidcConfigurer> oidcConfigCustomizer = customizer -> customizer.clientRegistrationEndpoint(Customizer.withDefaults());
        authorizationServerConfigurer.oidc(oidcConfigCustomizer);`
 2. Create initial access token 
 3. Register a client on /connect/register endpoint

**Expected behavior**
To be able to set the token_endpoint_auth_method to none on a client registration

**Comment by jgrandja** [comment] 2022-02-18 19:36
@emyasa Yes, this is intended behaviour. As per spec, in [5. Security Considerations](https://datatracker.ietf.org/doc/html/rfc7591#section-5):

> Public clients MAY register with an authorization server using this
   protocol, **if the authorization server's policy allows them**...

We're providing limited support for Public Clients since they are not secure in certain scenarios.

> is there another way to create public clients?

You could register a custom `@Bean` of type `RegisteredClientRepository` that returns a Public Client.

I'm going to close this as we're not looking to support dynamic registrations of Public Clients.

**Closed by jgrandja** 2022-02-18 19:36 UTC
Labels: type: bug

**Comment by emyasa** [comment] 2022-02-19 15:40
@jgrandja Thanks for the clarification, learned a lot. I'd gone through the route of using confidential client w/ BFF instead. 

By the way, I've filed a new enhancement, also related to dynamic client registration. Although a bit minor — since I currently got a workaround; however, I'm a bit conscious of using the Deprecated NoOpPassword encoder. More details here at [#631](https://github.com/spring-projects/spring-authorization-server/issues/631)
