### ISSUE TITLE
authorization fails with com.microsoft.sqlserver.jdbc.SQLServerException on SQL Server 2019

### ISSUE THREAD

**Issue by vincenzo-scia** [spring-projects/spring-authorization-server#1174] opened 2023-04-19 09:33 UTC
**Describe the bug**
Cannot authorize on existing registered client with SQL Server 2019.

> org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [INSERT INTO oauth2_authorization (id, registered_client_id, principal_name, authorization_grant_type, authorized_scopes, attributes, state, authorization_code_value, authorization_code_issued_at, authorization_code_expires_at, authorization_code_metadata, access_token_value, access_token_issued_at, access_token_expires_at, access_token_metadata, access_token_type, access_token_scopes, oidc_id_token_value, oidc_id_token_issued_at, oidc_id_token_expires_at, oidc_id_token_metadata, refresh_token_value, refresh_token_issued_at, refresh_token_expires_at, refresh_token_metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [null]; error code [0]; The string is not in a valid hex format.

> Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The string is not in a valid hex format.

is thrown for on insertion.

**To Reproduce**
Attempt to authorize via existing registered client, example url: `https://my.domain/my-application/oauth2/authorize?client_id=my-client&response_type=code&redirect_uri=https://my.domain/my-application/callback&scope=read write`

**Expected behavior**
 Should successfully authorize

**What seems to be happening**
It seems that spring-authorization-server strictly requires a datatype BLOB for some oauth2_authorization table columns (e.g. attributes, authorization_code_metadata) but the datatype BLOB seems not to be available on SQL Server 2019. Which datatype should be used on SQL Server 2019? In the attempt described above, VARBINARY is being used instead of BLOB.

**Comment by jgrandja** [comment] 2023-04-19 19:14
@vincenzo-scia Closing this as a duplicate of gh-550.

For additional details, please see this [comment](https://github.com/spring-projects/spring-authorization-server/issues/550#issuecomment-999750559).

**Closed by jgrandja** 2023-04-19 19:14 UTC
Labels: type: bug
