### ISSUE TITLE
TokenRequestValidation: parameter 'redirect_uri' can be omitted

### ISSUE THREAD

**Issue by itsmariohere** [spring-projects/spring-authorization-server#709] opened 2022-04-29 08:36 UTC
**Describe the bug**
In a request of a token to the tokenEndpoint (using client method authentication private_key_jwt) the 'redirect_uri' parameter is mandatory if it's specified in the authorization request, but can be omissed and read from the authorization request. If it's specified, then it must be equals.

From OIDC specification https://openid.net/specs/openid-connect-core-1_0.html#TokenRequestValidation:

`Ensure that the redirect_uri parameter value is identical to the redirect_uri parameter value that was included in the initial Authorization Request. If the redirect_uri parameter value is not present when there is only one registered redirect_uri value, the Authorization Server MAY return an error (since the Client should have included the parameter) or MAY proceed without an error (since OAuth 2.0 permits the parameter to be omitted in this case).`

At the moment, it throws an _OAuth2AuthenticationException_ (invalid_grant).

**To Reproduce**
When a token request is valid, it can be reproduced omitting the 'redirect_uri' parameter.

**Expected behavior**
The 'redirect_uri' shouldn't be mandatory, but it must be equals, if present, to the 'request_uri' that was specified in the authorization request.

**Sample**
`if (StringUtils.hasText(authorizationRequest.getRedirectUri()) &&
				!authorizationRequest.getRedirectUri().equals(authorizationCodeAuthentication.getRedirectUri())) {
			throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_GRANT);
		}`

I'd say this evaluation is reversed: ONLY IF _authorizationCodeAuthentication.getRedirectUri()_ has text THEN it must be equals to _authorizationRequest.getRedirectUri()_.

**Comment by jgrandja** [comment] 2022-05-05 19:03
@itsmariohere The current logic...

```java
if (StringUtils.hasText(authorizationRequest.getRedirectUri()) &&
		!authorizationRequest.getRedirectUri().equals(authorizationCodeAuthentication.getRedirectUri())) {
	throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_GRANT);
}
```

...is correct as far as I can see. The validation only applies if the `redirect_uri` was supplied in the `OAuth2AuthorizationRequest`.

Can you provide a test that reproduces the issue you are having. You can start the test using something similar to [authenticateWhenInvalidRedirectUriThenThrowOAuth2AuthenticationException()](https://github.com/spring-projects/spring-authorization-server/blob/627ae617851d4da2077c12bfcb11ff2609088fce/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeAuthenticationProviderTests.java#L217).

**Comment by spring-projects-issues** [comment] 2022-05-13 11:16
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-05-20 11:16
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-05-20 11:16 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
