### ISSUE TITLE
0.4 and 1.0 version /oauth2/token request return scope is empty

### ISSUE THREAD

**Issue by zhangdberic** [spring-projects/spring-authorization-server#1018] opened 2022-12-21 07:07 UTC
When sending the /oauth2/token request, if the request does not have a scope parameter, the 0.3.1 version is different from (0.4.0 and 1.0.0). 0.3.1 can return all the scopes of the  RegisteredClient, while 0.4.0 and 1.0.0 do not return scopes.

View the OAuth2ClientCredentialsAuthenticationProvider code of three versions, and find that the implementation is different.

0.3.1 The version is implemented as follows:
`Set<String> authorizedScopes = registeredClient.getScopes();		// Default to configured scopes
		if (!CollectionUtils.isEmpty(clientCredentialsAuthentication.getScopes())) {
			for (String requestedScope : clientCredentialsAuthentication.getScopes()) {
				if (!registeredClient.getScopes().contains(requestedScope)) {
					throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_SCOPE);
				}
			}
			authorizedScopes = new LinkedHashSet<>(clientCredentialsAuthentication.getScopes());
		}`
		

The 0.4.0 and 1.0.0 versions are implemented as follows:
`
		Set<String> authorizedScopes = Collections.emptySet();
		if (!CollectionUtils.isEmpty(clientCredentialsAuthentication.getScopes())) {
			for (String requestedScope : clientCredentialsAuthentication.getScopes()) {
				if (!registeredClient.getScopes().contains(requestedScope)) {
					throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_SCOPE);
				}
			}
			authorizedScopes = new LinkedHashSet<>(clientCredentialsAuthentication.getScopes());
		}
`

This change has a great impact on the client credentials mode, because we use scope to limit permissions.

Is this change in the rules correct?

**Comment by jgrandja** [comment] 2022-12-21 10:57
Closing as duplicate of gh-780

**Closed by jgrandja** 2022-12-21 10:57 UTC
Labels: type: bug
