### ISSUE TITLE
OAuth2TokenEndpointConfigurer custom AuthenticationProvider

### ISSUE THREAD

**Issue by jymot** [spring-projects/spring-authorization-server#437] opened 2021-09-09 02:05 UTC
**Expected Behavior**
I want to add a custom `AuthenticationProvider`through the `authenticationProvider` method of `OAuth2TokenEndpointConfigurer`, and I want to keep the `AuthenticationProvider` provided by default.

**Current Behavior**
If I add a new `AuthenticationProvider` I cannot keep the default`AuthenticationProvider`, because I see the following code from `OAuth2TokenEndpointConfigurer`
```java
	<B extends HttpSecurityBuilder<B>> void init(B builder) {
		ProviderSettings providerSettings = OAuth2ConfigurerUtils.getProviderSettings(builder);
		this.requestMatcher = new AntPathRequestMatcher(
				providerSettings.getTokenEndpoint(), HttpMethod.POST.name());

		List<AuthenticationProvider> authenticationProviders =
				!this.authenticationProviders.isEmpty() ?
						this.authenticationProviders :
						createDefaultAuthenticationProviders(builder);
		authenticationProviders.forEach(authenticationProvider ->
				builder.authenticationProvider(postProcess(authenticationProvider)));
	}
```
If `this.authenticationProviders` is not empty, then the default `AuthenticationProvider` will not be created.

If I want to achieve my goal, I must manually add the default `AuthenticationProvider` and my custom implementation together. I think this design is not very flexible.

**Context**
Is it possible to change the `private <B extends HttpSecurityBuilder<B>> List<AuthenticationProvider> createDefaultAuthenticationProviders(B builder) `method to `public`, or add a new method to add the default `AuthenticationProviders`

**Comment by jgrandja** [comment] 2021-09-21 19:55
Closing as duplicate of #417

**Closed by jgrandja** 2021-09-21 19:55 UTC
Labels: type: enhancement
