### ISSUE TITLE
After upgrading 0.1.0 -> 0.2.0, 401 when hitting /oauth2/authorize

### ISSUE THREAD

**Issue by nickmelis** [spring-projects/spring-authorization-server#434] opened 2021-09-07 12:37 UTC
**Describe the bug**
I have upgraded my application to the latest release (0.2.0), and since then I've noticed that all the calls to `/oauth/authorize` fail with a 401 status code. If I'm not mistaken, the previous behaviour was a plain redirect to the login page if not authenticated, and a plain redirect to `redirect_uri` when user is authenticated. Something has changed in between the two versions. I'm just not sure what/where.

**To Reproduce**
GET to http://auth-server:9000/oauth2/authorize?response_type=code&client_id=myClient&scope=openid%20email&state=vjTyJ6tQWG-baeviAJ0QC-i7ZxJQJ_WKF8gElFYM0r0%3D&redirect_uri=http://my-client&nonce=XXXX

**Expected behavior**
When user is not authenticated, it should redirect to login page, when user is authenticated, it should redirect to `redirect_uri`

**Sample**
Web security config:
```
@Import (OAuth2AuthorizationServerConfiguration.class)
public class WebSecurityConfiguration {

  @Bean
  SecurityFilterChain defaultSecurityFilterChain(HttpSecurity http) throws Exception {
    return http.authorizeRequests(authorizeRequests -> authorizeRequests
      .anyRequest().authenticated())
      .formLogin(loginConfigurer -> loginConfigurer
        .loginPage("/client")
        .loginProcessingUrl("/login")
        .successHandler(customAuthenticationSuccessHandler)
        .failureHandler(customAuthenticationFailureHandler)
        .permitAll())
      .logout(logoutConfigurer -> logoutConfigurer
        .logoutSuccessHandler(customLogoutSuccessHandler)
        .logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
      .addFilterBefore(customUsernamePasswordAuthenticationFilter, UsernamePasswordAuthenticationFilter.class)
      .build();
  }
}
```
App config:
```
  @Bean
  public RegisteredClientRepository registeredClientRepository() {
    RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
      .clientId(CLIENT_ID)
      .clientSecret(CLIENT_SECRET)
      .clientAuthenticationMethod(new ClientAuthenticationMethod("basic"))
      .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
      .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
      .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
      .redirectUri(REDIRECT_URI)
      .scope(OidcScopes.OPENID)
      .scope(OidcScopes.EMAIL)
      .clientSettings(ClientSettings.builder()
        .requireAuthorizationConsent(false)
        .build())
      .tokenSettings(TokenSettings.builder()
        .accessTokenTimeToLive("P30M")
        .refreshTokenTimeToLive("P24H")
        .reuseRefreshTokens(false)
        .build())
      .build();
    return new InMemoryRegisteredClientRepository(registeredClient);
  }

  @Bean
  public ProviderSettings providerSettings(AuthenticationProperties authenticationProperties) {
    return ProviderSettings.builder()
      .issuer(SERVER_URI)
      .build();
  }

```

Anyone able to help please?

**Comment by sjohnr** [comment] 2021-09-09 15:02
Hi @nickmelis, thanks for the report. Would you be able to provide a more concrete sample? The provided code leaves a few things out, for example `new ClientAuthenticationMethod(...)`. You'll want to make sure that you have provided a complete [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by sjohnr** [comment] 2021-09-09 15:29
@nickmelis, one additional thing to check. It looks like you're importing the default configuration using `@Import` which does not add form login support. Instead try the following:

```java
@Configuration
public class WebSecurityConfiguration {

	@Bean
	@Order(Ordered.HIGHEST_PRECEDENCE)
	public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
		OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);
		return http.formLogin(Customizer.withDefaults()).build();
	}

        // additional SecurityFilterChain @Bean here with custom formLogin() config

}
```

**Comment by nickmelis** [comment] 2021-09-09 15:42
Hi @sjohnr, thanks for the reply. I have updated my first comment in regards to ClientAuthenticationMethod. I generally use "basic". Also, I am indeed `@Import` -ing `OAuth2AuthorizationServerConfiguration`, and then defining my formLogin in the `defaultSecurityFilterChain` method. It used to work with the previous 0.1.0 version, so I'm not quite clear if something has changed in the meantime. 
I'll try defining the `SecurityFilterChain` bean as you described and see if it makes any difference. Thanks

**Comment by sjohnr** [comment] 2021-09-09 19:26
There are in fact a number of things that have changed. Using "basic" is now deprecated, as we have constants for `ClientAuthenticationMethod.CLIENT_SECRET_BASIC` => "client_secret_basic", etc. that are used instead. I'm not sure the difference in behavior between 0.1.0 and 0.2.0, but I would encourage you to start fresh from the samples available in this project with 0.2.0 and build back up from there. Since that is the first supported release, you will want to re-baseline your project starting from that sample, as anything prior to 0.2.0 is not officially supported. I think you'll find a number of small changes to the working example with 0.2.0.

Let us know if this brings you back to a working state.

**Comment by nickmelis** [comment] 2021-09-13 10:11
Ok, apparently what brought my authorisation server back to life was a combination of [@sjohnr 's comment](https://github.com/spring-projects/spring-authorization-server/issues/434#issuecomment-916205101), plus the fact that, when defining the `RegisteredClient`, the `clientSecret` now seems to have to go through `passwordEncoder`, which wasn't the case before: 
```
RegisteredClient registeredClient = RegisteredClient.withId(id)
      .clientId(clientId)
      .clientSecret(passwordEncoder.encode(clientSecret))
```
Unfortunately I only realised what was failing (`invalid_client`) error only after spending a good few hours debugging.
Everything else was just pure refactoring (method names change, etc) and it was pretty straightforward.

**Comment by fyeeme** [comment] 2021-09-13 13:47
@nickmelis  you saved my time!

just change 

```java
  var registeredClient = RegisteredClient.withId("client")
                .clientId("client")
                .clientSecret("client")
```
to 
```java
  var registeredClient = RegisteredClient.withId("client")
                .clientId("client")
                .clientSecret(passwordEncoder.encode("client"))
```

and the problem will be solved.

in fact  if  I debug `OAuth2ClientAuthenticationProvider`, I'll find why  this will happen

**Comment by sjohnr** [comment] 2021-09-13 14:09
Thanks @nickmelis. I'm going to close this, but feel free to add any additional clarifying comments if it's helpful in moving past this issue for other folks.

**Closed by sjohnr** 2021-09-13 14:09 UTC
Labels: status: feedback-provided, type: bug
