### ISSUE TITLE
Allow configuring OpenID Connect Discovery endpoint path

### ISSUE THREAD

**Issue by lsteffen1** [spring-projects/spring-authorization-server#675] opened 2022-04-01 14:57 UTC
**Expected Behavior**
The path of the OpenID Connect Discovery endpoint can be configured. (e.g. in ProviderSettings like done for jwkSetEndpoint)

**Current Behavior**
The path is hard-coded to /.well-known/openid-configuration

**Context**
We want to provide the endpoints of the spring-authorization-server library within a servlet which listens to a specific path. The old deprecated spring library currently runs with another path. Both of this versions need a separate path for the Discovery endpoint. This means for us the Discovery Endpoints should be available in e.g. /oidc/v2/.well-known/openid-configuration.
Right now this path seams to be hard-coded and cannot be replaced. (OidcProviderConfigurationEndpointFilter, OidcConfigurer)

**Comment by jgrandja** [comment] 2022-04-19 18:31
Closing as duplicate of gh-512. See [comment](https://github.com/spring-projects/spring-authorization-server/issues/512#issuecomment-989742944)

**Closed by jgrandja** 2022-04-19 18:31 UTC
Labels: type: enhancement
